name: TownyWaypoints
version: '1.0'
main: net.mvndicraft.townywaypoints.TownyWaypoints
description: Configurable Waypoints as Towny plots
api-version: '1.20'
folia-supported: true
dependencies:
  server:
    Towny:
      load: BEFORE
      required: true
    Vault:
      load: BEFORE
      required: true
permissions:
  townywaypoints.admin:
    description: "Allows use of the reload command and disables cooldown/distance/p2p check on travel."
    default: op